databaseChangeLog:
  - changeSet:
      id: environment_deletion
      author: lpollo
      changes:
        - createTable:
            tableName: environment_deletion
            columns:
              - column:
                  name: environment_uid
                  type: char(26)
                  constraints:
                    primaryKey: true
                    foreignKeyName: fk_environment_deletion_environment
                    referencedTableName: environment
                    referencedColumnNames: uid
                    deleteCascade: true
              - column:
                  name: last_checked_at
                  type: timestamp(3)
                  constraints:
                    nullable: false
        - createIndex:
            indexName: environment_deletion_last_checked_at_idx
            tableName: environment_deletion
            columns:
              - column:
                  name: last_checked_at
